### ISSUE TITLE
macOS version?

### ISSUE THREAD

**Issue by agustif** [rvpanoz/luna#31]
Why no macOS support?

**Comment by rvpanoz** [comment]
Hi agustif,

I will try to support the macOS in the next release of the app. I did not include it now because I did not have the time to test it correctly on mac based systems.

**Comment by agustif** [comment]
@rvpanoz, sure, that totally makes sense, let me know if I can help building/testing on MacOS, thanks for the great work!

**Comment by rvpanoz** [comment]
thank you for your support. Maybe I will need your help. :)

I will contact you when I am ready.

Thanks again.

**Comment by madsnedergaard** [comment]
Hey @rvpanoz, I'll have a look and see if I can get it running on macOS :)

**Comment by rvpanoz** [comment]
@madsnedergaard thank you, I really appreciate it.

**Comment by madsnedergaard** [comment]
Hmm, this wasn't quite the easy fix as I first thought ;)
Running the app in dev (through electron) works fine, the issue is that once the app is packaged we get a different environment. So executing `npm -v` no longer works, since $PATH is different from normal. 

See the following issues for more information:
https://github.com/nodejs/installer/issues/18
https://github.com/electron-userland/electron-builder/issues/880#issuecomment-258600731

I'll dig further and see if I can find a solution.

**Comment by rvpanoz** [comment]
super! :+1:
